name: health_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.6
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  rxdart: ^0.26.0
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  # barcode_scan: ^3.0.0
  url_launcher: ^6.0.7
  flutter_blue: ^0.8.0
  image_picker: ^0.8.4+4
  cron: ^0.3.0
  flutter_echarts: ^2.1.0
  jwt_decoder: ^2.0.1
  percent_indicator: ^3.0.1
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  firebase_analytics: ^8.1.2
  geolocator: ^7.2.0
  photo_view: ^0.11.1
  protobuf: ^2.0.0
  page_transition: ^2.0.2
  table_calendar: ^3.0.1
  connectivity: ^3.0.6
  path_provider: ^2.0.2
  google_maps_flutter: ^2.0.6
  rive: ^0.7.32
  crypto: ^3.0.1
  cached_network_image: ^3.1.0+1

  
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/rives/
    - assets/images/ic-calendar.png
    - assets/images/ic-calendar-u.png
    - assets/images/ic-dashboard.png
    - assets/images/ic-dashboard-u.png
    - assets/images/ic-vital-sign.png
    - assets/images/ic-vital-sign-u.png
    - assets/images/ic-pop.png
    - assets/images/ic-field-phone.png
    - assets/images/ic-field-username.png
    - assets/images/ic-validate.png
    - assets/images/ic-otp.png
    - assets/images/ic-close.png
    - assets/images/ic-noti.png
    - assets/images/ic-noti-u.png
    - assets/images/avatar-default.jpg
    - assets/images/ic-snow.png
    - assets/images/ic-sleet.png
    - assets/images/ic-thunderstorm.png
    - assets/images/ic-light-rain.png
    - assets/images/ic-heavy-rain.png
    - assets/images/ic-heavy-cloud.png
    - assets/images/ic-showers.png
    - assets/images/ic-light-cloud.png
    - assets/images/ic-clear.png
    - assets/images/ic-night.png
    - assets/images/ic-temp.png
    - assets/images/ic-wind.png
    - assets/images/ic-hum.png
    - assets/images/ic-back-to-top.png
    - assets/images/ic-close-white.png
    - assets/images/ic-backward.png
    - assets/images/ic-light-mode.png
    - assets/images/ic-dark-mode.png
    - assets/images/ic-unlike.png
    - assets/images/ic-like.png
    - assets/images/ic-system-mode.png
    - assets/images/bg-calendar.png
    - assets/images/loading-news.png
    - assets/images/ic-warning.png
    - assets/images/ic-loading.png
    - assets/images/bg-wday.png
    - assets/images/bg-wnight.png
    - assets/images/ic-device.png
    - assets/images/ic-theme.png
    - assets/images/ic-information.png
    - assets/images/ic-gointo.png
    - assets/images/ic-dark-theme.png
    - assets/images/ic-light-theme.png
    - assets/images/ic-system-theme.png
    - assets/images/ic-checked.png
    - assets/images/ic-uncheck.png
    - assets/images/ic-success.png
    - assets/images/ic-search.png
    - assets/images/ic-bluetooth.png
    - assets/images/ic-reload.png
    - assets/images/ic-popUltil.png
    - assets/images/devices/device-amazfit.png
    - assets/images/devices/device-miband2.png
    - assets/images/devices/device-miband3.png
    - assets/images/devices/device-miband4.png
    - assets/images/devices/device-miband5.png
    - assets/images/devices/device-unknown.png
    - assets/images/devices/device-fite.png
    - assets/images/bg-device.png
    - assets/images/ic-heart-rate.png
    - assets/images/ic-blood-pressure.png
    - assets/images/ic-oxy.png
    - assets/images/ic-spo2.png
    - assets/images/ic-step-count.png
    - assets/images/ic-kcal.png
    - assets/images/ic-meter.png
    - assets/images/bg-activity.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    
  fonts:
    - family: NewYork
      fonts:
        - asset: assets/fonts/NewYork.ttf
        - asset: assets/fonts/NewYorkItalic.ttf
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
